packages:
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@swc/core'
  - '@valian/eslint-config'
  - esbuild
  - nx
  - protobufjs
  - re2
  - unrs-resolver

publicHoistPattern:
  - eslint-import-resolver-typescript

resolvePeersFromWorkspaceRoot: true
